services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: em-backend
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: em-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge
